spring:
  application:
    name: product-service
server:
  port: 8081

# Kafka topic configuration
kafka:
  topics:
    product-events: product-events
    inventory-events: inventory-events

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never
