apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ecommerce
resources:
  - 00-namespace.yaml
  - 01-configmap.yaml
  - 02-secret.yaml
  - 03-init-databases-job.yaml
  - 10-auth-service.yaml
  - 11-product-service.yaml
  - 12-inventory-service.yaml
  - 13-order-service.yaml
  - 14-api-gateway.yaml

